id: I5D4BDB95
legacy_id: P004618
ocr_import_info:
  bdrc_scan_id: W27214
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T05:43:52'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T06:55:37.123978+00:00'
last_modified: 2022-09-02 14:56:19.970614
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27214
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW27214
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆོས་འབྱུང་ངོ་མཚར་རྒྱ་མཚོ ༼སྔགས་འཕེལ་དགོན་པར་མ༽
  author: སྟག་ལུང་ཞབས་དྲུང་ངག་དབང་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.41095545566874814
  ocr_word_median_confidence_index: 0.3199999928474426
quality: null
bases:
  I1CZ1046:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1046
      total_pages: 732
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1046.txt
    statistics:
      ocr_word_median_confidence_index: 0.3199999928474426
      ocr_word_mean_confidence_index: 0.41095545566874814
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
