id: P004618
initial_creation_type: ocr
source_metadata:
  id: bdr:W27214
  title: ཆོས་འབྱུང་ངོ་མཚར་རྒྱ་མཚོ ༼སྔགས་འཕེལ་དགོན་པར་མ༽
  author: ''
  volumes:
    36cff05b3fa64f3aa2d68694b7ffc49e:
      image_group_id: I1CZ1046
      title: ''
      volume_number: 1
      total_pages: 732
